### PR TITLE
Add hotkeys for new diagram

### PR DESCRIPTION
**Pull request by acktsap**
Resolves https://github.com/zapthedingbat/drawio-obsidian/issues/16

### CODE REVIEW

**Comment by Chouffy** [comment]
@acktsap do you think you could share a build of yours with this commit?
I'm a bit afraid that it'll take time before we get a new release, as the last one is quite dated 😅

**Comment by Chouffy** [comment]
I was able to do a build: [dist.zip](https://github.com/zapthedingbat/drawio-obsidian/files/11421313/dist.zip)
Just drop it it in the `[Vault Directory]|\.obsidian\plugins\drawio-obsidian`

**Comment by balta2ar** [comment]
The first diagram is created using this plugin: https://github.com/jensmtg/obsidian-diagrams-net/

The second one using the plugin in this repo. Looks like this plugin adds a bit of margin. Would it be possible to look into it and reduce the margin, @acktsap?

image

**Comment by balta2ar** [comment]
this the function that adds margins
```
  private addViewBoxMarginToSvg(svg: SVGElement) {
    const margin = 10;
    const viewBox = svg.getAttribute("viewBox");
    const [a, b, c, d] = viewBox
      .split(" ")
      .map((x: string) => Number.parseFloat(x));
    svg.setAttribute(
      "viewBox",
      [a - margin, b - margin, c + margin * 2, d + margin * 2].join(" ")
    );
  }
}
```
used here:
```
    // Add margin to SVG
    this.addViewBoxMarginToSvg(svgDocument);
````

**Pull request merged**
