### PR TITLE
Obsidian & drawio Update

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Thanks a lot for this plugin! Being so used to drawio, I've been rather missing it whenever I used Obsidian. 😄 

I noticed that the drawio version was a bit older and had some odd behavior where the editor would open in the navigation pane, effectively breaking it and requiring a restart of Obsidian. With the Obsidian update, some functions were deprecated or removed, so I updated those.

I'm not very familiar with Obsidian plugin development and my front-end skills aren't the best, so forgive my ignorance if I missed something obvious.

I tried to run the automation part, but that was broken to begin with and I couldn't figure out what needs to be changed exactly.

Additionally, I added some instructions to the README, as it seems not as intuitive (see #60 / #54 / #45).

Let me know if there's anything that I should adjust 🙂

### CODE REVIEW

**Comment by szymonj99** [comment]
DrawIO just updated to `v20.3.6` what looks to be a few hours after your commit. Would it be worth reflecting this update in a new commit? 🤔

**Comment by eXpl0it3r** [comment]
Thanks for letting me know! I just rewrote the commit.

The funny part is, that I did actually already have the reference locally, but they must have tagged it between me checking the available tags on GitHub and me fetching the remote. 😄

**Comment by eXpl0it3r** [comment]
Thanks for merging this! 😄 

Anything I can help with to create a new release?

**Comment by lxq1** [comment]
请问可以发布一个新的release吗？

Can you release a new release?

**Comment by lxq1** [comment]
请问可以发布一个新的release吗？

Can you release a new release?

**Pull request merged**
